
import { Movie, Category } from './types';

export const ALL_CATEGORIES: Category[] = [
  Category.ACTION,
  Category.COMEDY,
  Category.DRAMA,
  Category.HORROR,
  Category.SCIFI,
  Category.ROMANCE,
  Category.THRILLER,
  Category.ANIMATION,
  Category.FANTASY,
];

export const INITIAL_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Inception',
    genre: Category.SCIFI,
    releaseDate: '2010-07-16',
    description: 'A thief who steals information by entering people\'s dreams.',
    posterUrl: 'https://picsum.photos/seed/inception/400/600',
    watchUrl: 'https://www.example.com/watch/inception',
  },
  {
    id: '2',
    title: 'The Dark Knight',
    genre: Category.ACTION,
    releaseDate: '2008-07-18',
    description: 'When the menace known as the Joker emerges from his mysterious past.',
    posterUrl: 'https://picsum.photos/seed/darkknight/400/600',
    watchUrl: 'https://www.example.com/watch/darkknight',
  },
  {
    id: '3',
    title: 'Pulp Fiction',
    genre: Category.DRAMA,
    releaseDate: '1994-10-14',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife.',
    posterUrl: 'https://picsum.photos/seed/pulpfiction/400/600',
    watchUrl: 'https://www.example.com/watch/pulpfiction',
  },
  {
    id: '4',
    title: 'The Matrix',
    genre: Category.SCIFI,
    releaseDate: '1999-03-31',
    description: 'A computer hacker learns about the true nature of his reality.',
    posterUrl: 'https://picsum.photos/seed/matrix/400/600',
    watchUrl: 'https://www.example.com/watch/matrix',
  },
  {
    id: '5',
    title: 'Forrest Gump',
    genre: Category.DRAMA,
    releaseDate: '1994-07-06',
    description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal.',
    posterUrl: 'https://picsum.photos/seed/forrestgump/400/600',
    watchUrl: 'https://www.example.com/watch/forrestgump',
  },
  {
    id: '6',
    title: 'Spirited Away',
    genre: Category.ANIMATION,
    releaseDate: '2001-07-20',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.',
    posterUrl: 'https://picsum.photos/seed/spiritedaway/400/600',
    watchUrl: 'https://www.example.com/watch/spiritedaway',
  },
  {
    id: '7',
    title: 'The Conjuring',
    genre: Category.HORROR,
    releaseDate: '2013-07-19',
    description: 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.',
    posterUrl: 'https://picsum.photos/seed/conjuring/400/600',
    watchUrl: 'https://www.example.com/watch/conjuring',
  },
  {
    id: '8',
    title: 'La La Land',
    genre: Category.ROMANCE,
    releaseDate: '2016-12-09',
    description: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
    posterUrl: 'https://picsum.photos/seed/lalaland/400/600',
    watchUrl: 'https://www.example.com/watch/lalaland',
  },
   {
    id: '9',
    title: 'Parasite',
    genre: Category.THRILLER,
    releaseDate: '2019-05-30',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    posterUrl: 'https://picsum.photos/seed/parasite/400/600',
    watchUrl: 'https://www.example.com/watch/parasite',
  },
  {
    id: '10',
    title: 'Avengers: Endgame',
    genre: Category.ACTION,
    releaseDate: '2019-04-26',
    description: 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.',
    posterUrl: 'https://picsum.photos/seed/endgame/400/600',
    watchUrl: 'https://www.example.com/watch/endgame',
  },
  {
    id: '11',
    title: 'Your Name',
    genre: Category.ANIMATION,
    releaseDate: '2016-08-26',
    description: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
    posterUrl: 'https://picsum.photos/seed/yourname/400/600',
    watchUrl: 'https://www.example.com/watch/yourname',
  },
  {
    id: '12',
    title: 'The Lord of the Rings: The Return of the King',
    genre: Category.FANTASY,
    releaseDate: '2003-12-17',
    description: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
    posterUrl: 'https://picsum.photos/seed/lotr/400/600',
    watchUrl: 'https://www.example.com/watch/lotr',
  }
];
